package in.hrsoftwares.hibernate;
// Generated 27 Aug, 2016 4:54:04 PM by Hibernate Tools 5.1.0.Beta1

/**
 * ActorInfo generated by hbm2java
 */
public class ActorInfo implements java.io.Serializable {

	private ActorInfoId id;

	public ActorInfo() {
	}

	public ActorInfo(ActorInfoId id) {
		this.id = id;
	}

	public ActorInfoId getId() {
		return this.id;
	}

	public void setId(ActorInfoId id) {
		this.id = id;
	}

}
