package in.hrsoftwares.hibernate;
// Generated 27 Aug, 2016 4:54:04 PM by Hibernate Tools 5.1.0.Beta1

/**
 * NicerButSlowerFilmList generated by hbm2java
 */
public class NicerButSlowerFilmList implements java.io.Serializable {

	private NicerButSlowerFilmListId id;

	public NicerButSlowerFilmList() {
	}

	public NicerButSlowerFilmList(NicerButSlowerFilmListId id) {
		this.id = id;
	}

	public NicerButSlowerFilmListId getId() {
		return this.id;
	}

	public void setId(NicerButSlowerFilmListId id) {
		this.id = id;
	}

}
