package in.hrsoftwares.hibernate;
// Generated 27 Aug, 2016 4:54:04 PM by Hibernate Tools 5.1.0.Beta1

/**
 * SalesByStore generated by hbm2java
 */
public class SalesByStore implements java.io.Serializable {

	private SalesByStoreId id;

	public SalesByStore() {
	}

	public SalesByStore(SalesByStoreId id) {
		this.id = id;
	}

	public SalesByStoreId getId() {
		return this.id;
	}

	public void setId(SalesByStoreId id) {
		this.id = id;
	}

}
