package in.hrsoftwares.hibernate;
// Generated 27 Aug, 2016 4:54:04 PM by Hibernate Tools 5.1.0.Beta1

/**
 * SalesByFilmCategory generated by hbm2java
 */
public class SalesByFilmCategory implements java.io.Serializable {

	private SalesByFilmCategoryId id;

	public SalesByFilmCategory() {
	}

	public SalesByFilmCategory(SalesByFilmCategoryId id) {
		this.id = id;
	}

	public SalesByFilmCategoryId getId() {
		return this.id;
	}

	public void setId(SalesByFilmCategoryId id) {
		this.id = id;
	}

}
