package in.hrsoftwares.hibernate;
// Generated 27 Aug, 2016 4:54:04 PM by Hibernate Tools 5.1.0.Beta1

/**
 * StaffList generated by hbm2java
 */
public class StaffList implements java.io.Serializable {

	private StaffListId id;

	public StaffList() {
	}

	public StaffList(StaffListId id) {
		this.id = id;
	}

	public StaffListId getId() {
		return this.id;
	}

	public void setId(StaffListId id) {
		this.id = id;
	}

}
